import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { StoneJarCard } from "@/components/stones/StoneJarCard";
import { getPublishedStoneJars } from "@/lib/queries/stones";
export const metadata: Metadata = { title: "Lọ đá phong thủy | Huyền Cảnh", description: "Khám phá các lọ đá phong thủy được phối hợp theo ý nghĩa, nguồn năng lượng và không gian sử dụng." };
type Props = { searchParams: Promise<{ q?: string; page?: string }> };
export default async function StoneJarsPage({ searchParams }: Props) { const params = await searchParams; const result = await getPublishedStoneJars({ q: params.q, page: Number(params.page) || 1 }); const pages = Math.max(1, Math.ceil(result.count / result.pageSize)); const pageHref = (page: number) => `/lo-da-phong-thuy?${new URLSearchParams({ ...(params.q ? { q: params.q } : {}), page: String(page) })}`; return <><Header /><main className="min-h-screen px-5 pb-24 pt-32 md:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-antique-gold">Phối hợp năng lượng</p><h1 className="mt-4 font-serif text-5xl text-ivory md:text-7xl">Lọ đá phong thủy</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-stone-mist">Những tổ hợp khoáng vật dành cho bàn làm việc, không gian sống và món quà mang ý nghĩa riêng.</p><form className="mt-10 flex max-w-xl gap-3 border-y border-gilded/30 py-5"><input name="q" defaultValue={params.q} placeholder="Tìm lọ đá" className="min-h-11 min-w-0 flex-1 rounded-sm border border-gilded/50 bg-obsidian px-3 text-ivory" /><button className="min-h-11 rounded-full bg-antique-gold px-5 text-sm font-semibold text-obsidian">Tìm kiếm</button></form>{result.jars.length ? <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{result.jars.map((jar) => <StoneJarCard key={jar.id} jar={jar} />)}</div> : <section className="mt-10 rounded-lg border border-gilded/40 bg-card-deep/75 p-10 text-center text-stone-mist">Chưa có lọ đá phù hợp.</section>}<nav className="mt-10 flex justify-between text-sm">{result.page > 1 ? <Link href={pageHref(result.page - 1)} className="text-antique-gold">← Trang trước</Link> : <span />}{result.page < pages ? <Link href={pageHref(result.page + 1)} className="text-antique-gold">Trang sau →</Link> : <span />}</nav></div></main><Footer /></>; }
