import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { StoneCard } from "@/components/stones/StoneCard";
import { getPublishedStones } from "@/lib/queries/stones";

export const metadata: Metadata = { title: "Đá phong thủy | Huyền Cảnh", description: "Khám phá ý nghĩa, công dụng, mệnh và cung hoàng đạo phù hợp với từng loại đá phong thủy." };
type Props = { searchParams: Promise<{ q?: string; element?: string; color?: string; benefit?: string; page?: string }> };
function href(params: Awaited<Props["searchParams"]>, page: number) { const query = new URLSearchParams(Object.entries(params).filter(([key, value]) => key !== "page" && value) as [string, string][]); query.set("page", String(page)); return `/da-phong-thuy?${query}`; }
export default async function StonesPage({ searchParams }: Props) { const params = await searchParams; const result = await getPublishedStones({ q: params.q, element: params.element, color: params.color, benefit: params.benefit, page: Number(params.page) || 1 }); const pages = Math.max(1, Math.ceil(result.count / result.pageSize)); return <><Header /><main className="min-h-screen px-5 pb-24 pt-32 md:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-antique-gold">Khoáng vật và năng lượng</p><h1 className="mt-4 font-serif text-5xl font-semibold text-ivory md:text-7xl">Đá phong thủy</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-stone-mist">Tìm loại đá đồng điệu với mệnh, sắc màu và điều bạn đang muốn nuôi dưỡng.</p>
  <form className="mt-10 grid gap-3 border-y border-gilded/30 py-5 sm:grid-cols-2 lg:grid-cols-5"><input name="q" defaultValue={params.q} placeholder="Tìm theo tên đá" className="min-h-11 rounded-sm border border-gilded/50 bg-obsidian px-3 text-ivory" /><input name="element" defaultValue={params.element} placeholder="Mệnh phù hợp" className="min-h-11 rounded-sm border border-gilded/50 bg-obsidian px-3 text-ivory" /><input name="color" defaultValue={params.color} placeholder="Màu sắc" className="min-h-11 rounded-sm border border-gilded/50 bg-obsidian px-3 text-ivory" /><input name="benefit" defaultValue={params.benefit} placeholder="Công dụng" className="min-h-11 rounded-sm border border-gilded/50 bg-obsidian px-3 text-ivory" /><button className="min-h-11 rounded-full bg-antique-gold px-5 text-sm font-semibold text-obsidian">Tìm đá</button></form>
  {result.stones.length ? <div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{result.stones.map((stone) => <StoneCard key={stone.id} stone={stone} />)}</div> : <section className="mt-10 rounded-lg border border-gilded/40 bg-card-deep/75 p-10 text-center text-stone-mist">Chưa tìm thấy loại đá phù hợp. Hãy thử điều kiện khác.</section>}<nav className="mt-10 flex justify-between text-sm">{result.page > 1 ? <Link href={href(params, result.page - 1)} className="text-antique-gold">← Trang trước</Link> : <span />}{result.page < pages ? <Link href={href(params, result.page + 1)} className="text-antique-gold">Trang sau →</Link> : <span />}</nav></div></main><Footer /></>; }
