import Link from "next/link";
import { MarkdownContent } from "@/components/blog/MarkdownContent";
import { AdminStoneActions } from "@/components/stones/AdminStoneActions";
import { StoneImage } from "@/components/stones/StoneImage";
import { requireAdminProfile } from "@/lib/auth/admin";
import { getAdminStoneJar } from "@/lib/queries/stones";
import { stoneStatusLabels } from "@/lib/validations/stones";
export const dynamic = "force-dynamic";
export default async function AdminJarDetail({ params }: { params: Promise<{ id: string }> }) { await requireAdminProfile(); const { id } = await params; const jar = await getAdminStoneJar(id); return <main className="min-h-screen px-5 py-10 md:px-8"><div className="mx-auto max-w-6xl"><Link href="/admin/lo-da" className="text-sm text-antique-gold">← Quản lý lọ đá</Link><div className="mt-4 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="font-serif text-5xl text-ivory">{jar.name}</h1><p className="mt-2 text-stone-mist">{stoneStatusLabels[jar.status]} · /{jar.slug}</p></div><AdminStoneActions item={jar} kind="jar" /></div><section className="mt-8 grid gap-8 rounded-lg border border-gilded/40 bg-card-deep/75 p-5 lg:grid-cols-[320px_1fr]"><StoneImage src={jar.featured_image} alt={jar.name} /><div><p className="text-antique-gold">{jar.price == null ? jar.price_label : `${jar.price.toLocaleString("vi-VN")}đ`}</p>{jar.short_description ? <p className="mt-3 text-lg text-stone-mist">{jar.short_description}</p> : null}{jar.content ? <div className="mt-8"><MarkdownContent content={jar.content} /></div> : null}</div></section><section className="mt-8"><h2 className="font-serif text-3xl text-ivory">Các loại đá trong lọ</h2><div className="mt-4 grid gap-3">{jar.items.length ? jar.items.map((item) => <article key={item.id} className="grid gap-4 rounded-lg border border-gilded/30 bg-card-deep/60 p-4 sm:grid-cols-[100px_1fr]"><StoneImage src={item.stone.featured_image} alt={item.stone.name} square sizes="100px" /><div><h3 className="font-serif text-2xl text-ivory">{item.stone.name}</h3><p className="text-xs text-antique-gold">{stoneStatusLabels[item.stone.status]}{item.quantity ? ` · ${item.quantity}` : ""}</p>{item.description ? <p className="mt-2 text-sm text-stone-mist">{item.description}</p> : null}</div></article>) : <p className="text-stone-mist">Chưa có loại đá nào.</p>}</div></section></div></main>; }
