"use client";

import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { useMemo, useRef, useState, useTransition } from "react";

import { MarkdownToolbar } from "@/components/stones/MarkdownToolbar";
import { StoneImage } from "@/components/stones/StoneImage";
import { createStoneJar, updateStoneJar, type StoneActionState } from "@/lib/actions/stones";
import { slugifyVietnamese } from "@/lib/blog/slug";
import { stoneStatusLabels } from "@/lib/validations/stones";
import type { StoneJarDetail, StoneSummary } from "@/types/stones";

type EditorItem = { stoneId: string; description: string; quantity: string; displayOrder: number };
const empty: StoneActionState = { ok: false, message: "" };
const input = "min-h-11 rounded-sm border border-gilded/50 bg-obsidian px-3 text-ivory focus:outline-none focus:ring-2 focus:ring-antique-gold";
const area = `${input} py-2`;

export function StoneJarForm({ jar, stones }: { jar?: StoneJarDetail; stones: StoneSummary[] }) {
  const [pending, start] = useTransition(); const [message, setMessage] = useState<StoneActionState>(empty);
  const [name, setName] = useState(jar?.name ?? ""); const [slug, setSlug] = useState(jar?.slug ?? ""); const [slugTouched, setSlugTouched] = useState(Boolean(jar));
  const [gallery, setGallery] = useState(jar?.gallery ?? []); const [search, setSearch] = useState("");
  const [items, setItems] = useState<EditorItem[]>(jar?.items.map((item) => ({ stoneId: item.stone_id, description: item.description ?? "", quantity: item.quantity ?? "", displayOrder: item.display_order })) ?? []);
  const contentRef = useRef<HTMLTextAreaElement>(null); const selected = useMemo(() => new Set(items.map((item) => item.stoneId)), [items]);
  const options = useMemo(() => stones.filter((stone) => !selected.has(stone.id) && stone.name.toLocaleLowerCase("vi").includes(search.toLocaleLowerCase("vi"))), [search, selected, stones]);
  function reorder(index: number, direction: -1 | 1) { setItems((current) => { const target = index + direction; if (target < 0 || target >= current.length) return current; const next = [...current]; [next[index], next[target]] = [next[target], next[index]]; return next.map((item, displayOrder) => ({ ...item, displayOrder })); }); }
  function patchItem(index: number, patch: Partial<EditorItem>) { setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item)); }
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); data.set("gallery", JSON.stringify(gallery)); data.set("items", JSON.stringify(items.map((item, displayOrder) => ({ ...item, displayOrder })))); if (jar) { data.set("id", jar.id); data.set("expectedUpdatedAt", jar.updated_at); } start(async () => setMessage(await (jar ? updateStoneJar : createStoneJar)(empty, data))); }
  return <form onSubmit={submit} encType="multipart/form-data" className="grid gap-6 rounded-lg border border-gilded/40 bg-card-deep/80 p-5"><fieldset disabled={pending} className="grid gap-6 disabled:opacity-70">
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm text-stone-mist">Tên lọ đá<input name="name" value={name} onChange={(e) => { setName(e.target.value); if (!slugTouched) setSlug(slugifyVietnamese(e.target.value)); }} required className={input} /></label><label className="grid gap-2 text-sm text-stone-mist">Slug<input name="slug" value={slug} onChange={(e) => { setSlug(e.target.value); setSlugTouched(true); }} required className={input} /></label></div>
    <label className="grid gap-2 text-sm text-stone-mist">Mô tả ngắn<textarea name="shortDescription" defaultValue={jar?.short_description ?? ""} rows={3} className={area} /></label>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm text-stone-mist">URL ảnh đại diện<input name="featuredImage" defaultValue={jar?.featured_image ?? ""} className={input} /></label><label className="grid gap-2 text-sm text-stone-mist">Tải ảnh đại diện<input name="featuredImageFile" type="file" accept="image/jpeg,image/png,image/webp" className={`${input} py-2`} /></label></div>
    <section className="grid gap-4 rounded-lg border border-gilded/30 p-4"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl text-ivory">Thư viện ảnh</h2><span className="text-xs text-stone-mist">Tối đa 20 ảnh</span></div><input name="galleryFiles" type="file" multiple accept="image/jpeg,image/png,image/webp" className={`${input} py-2`} />{gallery.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{gallery.map((url) => <div key={url} className="grid gap-2"><StoneImage src={url} alt="Ảnh thư viện lọ đá" /><button type="button" onClick={() => setGallery((list) => list.filter((item) => item !== url))} className="inline-flex min-h-9 items-center justify-center gap-2 rounded-sm border border-wine/70 text-xs text-red-100"><Trash2 size={14} />Gỡ ảnh</button></div>)}</div> : null}</section>
    <div className="grid gap-3"><MarkdownToolbar textareaRef={contentRef} /><label className="grid gap-2 text-sm text-stone-mist">Câu chuyện và giới thiệu<textarea ref={contentRef} name="content" defaultValue={jar?.content ?? ""} rows={16} className={`${area} font-mono text-sm`} /></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm text-stone-mist">Ý nghĩa và nguồn năng lượng<textarea name="meaning" defaultValue={jar?.meaning ?? ""} rows={6} className={area} /></label><label className="grid gap-2 text-sm text-stone-mist">Cách sử dụng và vị trí đặt<textarea name="usage" defaultValue={jar?.usage ?? ""} rows={6} className={area} /></label></div>
    <section className="grid gap-4 rounded-lg border border-gilded/30 p-4"><div><h2 className="font-serif text-2xl text-ivory">Các loại đá trong lọ</h2><p className="mt-1 text-sm text-stone-mist">Tìm, thêm, ghi chú và sắp xếp bằng nút lên xuống.</p></div><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input aria-label="Tìm loại đá" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Tìm loại đá" className={input} /><select id="stone-option" aria-label="Chọn loại đá để thêm vào lọ" className={input} defaultValue=""><option value="">Chọn loại đá</option>{options.map((stone) => <option key={stone.id} value={stone.id}>{stone.name} · {stoneStatusLabels[stone.status]}</option>)}</select><button type="button" onClick={() => { const select = document.getElementById("stone-option") as HTMLSelectElement | null; if (select?.value && !selected.has(select.value)) { setItems((current) => [...current, { stoneId: select.value, description: "", quantity: "", displayOrder: current.length }]); select.value = ""; } }} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-antique-gold px-4 text-sm text-antique-gold"><Plus size={16} />Thêm</button></div>
      <div className="grid gap-3">{items.length === 0 ? <p className="rounded-sm border border-gilded/25 p-4 text-sm text-stone-mist">Chưa chọn loại đá nào.</p> : items.map((item, index) => { const stone = stones.find((option) => option.id === item.stoneId); if (!stone) return null; return <article key={item.stoneId} className="grid gap-3 rounded-lg border border-gilded/30 bg-obsidian/40 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-serif text-xl text-ivory">{index + 1}. {stone.name}</h3>{stone.status !== "published" ? <p role="alert" className="text-xs text-red-200">Cảnh báo: loại đá này đang {stoneStatusLabels[stone.status].toLocaleLowerCase("vi")}.</p> : null}</div><div className="flex gap-2"><button type="button" title="Đưa lên" disabled={index === 0} onClick={() => reorder(index, -1)} className="grid size-9 place-items-center rounded-sm border border-gilded/50 disabled:opacity-40"><ArrowUp size={15} /></button><button type="button" title="Đưa xuống" disabled={index === items.length - 1} onClick={() => reorder(index, 1)} className="grid size-9 place-items-center rounded-sm border border-gilded/50 disabled:opacity-40"><ArrowDown size={15} /></button><button type="button" title="Gỡ khỏi lọ" onClick={() => setItems((current) => current.filter((_, itemIndex) => itemIndex !== index).map((entry, displayOrder) => ({ ...entry, displayOrder })))} className="grid size-9 place-items-center rounded-sm border border-wine/70 text-red-100"><Trash2 size={15} /></button></div></div><div className="grid gap-3 md:grid-cols-[1fr_180px]"><label className="grid gap-1 text-xs text-stone-mist">Vai trò hoặc ý nghĩa<textarea value={item.description} onChange={(e) => patchItem(index, { description: e.target.value })} rows={3} className={area} /></label><label className="grid gap-1 text-xs text-stone-mist">Số lượng hoặc tỷ lệ<input value={item.quantity} onChange={(e) => patchItem(index, { quantity: e.target.value })} className={input} /></label></div></article>; })}</div>
    </section>
    <div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm text-stone-mist">Giá tham khảo<input name="price" type="number" min="0" step="1000" defaultValue={jar?.price ?? ""} className={input} /></label><label className="grid gap-2 text-sm text-stone-mist">Nhãn khi không có giá<input name="priceLabel" defaultValue={jar?.price_label ?? "Liên hệ"} className={input} /></label><label className="grid gap-2 text-sm text-stone-mist">Thông điệp liên hệ tùy chỉnh<input name="contactMessage" defaultValue={jar?.contact_message ?? ""} placeholder="Có thể dùng [Tên lọ đá] và [Đường dẫn trang chi tiết]" className={input} /></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm text-stone-mist">SEO title<input name="seoTitle" defaultValue={jar?.seo_title ?? ""} className={input} /></label><label className="grid gap-2 text-sm text-stone-mist">SEO description<input name="seoDescription" defaultValue={jar?.seo_description ?? ""} className={input} /></label></div>
    <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm text-stone-mist">Trạng thái<select name="status" defaultValue={jar?.status ?? "draft"} className={input}>{Object.entries(stoneStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="flex items-center gap-3 self-end pb-3 text-sm text-stone-mist"><input name="isFeatured" type="checkbox" defaultChecked={jar?.is_featured ?? false} />Nội dung nổi bật</label></div>
  </fieldset><button disabled={pending} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-antique-gold px-5 text-sm font-semibold text-obsidian disabled:opacity-60"><Plus size={16} />{pending ? "Đang lưu..." : jar ? "Lưu lọ đá" : "Tạo lọ đá"}</button>{message.message ? <div role="status" className={message.ok ? "text-antique-gold" : "text-red-200"}><p>{message.message}</p>{!message.ok && message.fieldErrors ? <ul className="mt-2 list-disc pl-5 text-sm">{Object.entries(message.fieldErrors).flatMap(([field, errors]) => errors.map((error) => <li key={`${field}-${error}`}>{error}</li>))}</ul> : null}</div> : null}</form>;
}
