import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { MarkdownContent } from "@/components/blog/MarkdownContent";
import { StoneImage } from "@/components/stones/StoneImage";
import { StoneJarCard } from "@/components/stones/StoneJarCard";
import { getPublishedStoneBySlug } from "@/lib/queries/stones";
const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://huyen-canh.local";
const absoluteImageUrl = (url: string | null) => url ? new URL(url, `${baseUrl}/`).toString() : undefined;
type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const stone = await getPublishedStoneBySlug(slug); if (!stone) return { title: "Không tìm thấy loại đá", robots: { index: false } }; const title = stone.seo_title || stone.name; const description = stone.seo_description || stone.short_description || "Đá phong thủy tại Huyền Cảnh."; const url = `${baseUrl}/da-phong-thuy/${stone.slug}`; const image = absoluteImageUrl(stone.featured_image); return { title, description, alternates: { canonical: url }, openGraph: { title, description, url, type: "article", images: image ? [{ url: image, alt: stone.name }] : undefined } }; }
function TextSection({ title, value }: { title: string; value: string | null }) { return value ? <section className="border-t border-gilded/30 py-9"><h2 className="font-serif text-3xl text-ivory">{title}</h2><p className="mt-4 whitespace-pre-line text-base leading-8 text-stone-mist">{value}</p></section> : null; }
export default async function StoneDetailPage({ params }: Props) { const { slug } = await params; const stone = await getPublishedStoneBySlug(slug); if (!stone) notFound(); const images = [...new Set([stone.featured_image, ...stone.gallery].filter((url): url is string => Boolean(url)))]; return <><Header /><main className="min-h-screen px-5 pb-24 pt-32 md:px-8"><div className="mx-auto max-w-7xl"><nav className="text-sm text-stone-mist"><Link href="/da-phong-thuy" className="text-antique-gold">Đá phong thủy</Link> / {stone.name}</nav><section className="grid gap-10 py-12 lg:grid-cols-[0.9fr_1fr] lg:items-center"><StoneImage src={stone.featured_image} alt={stone.name} priority square /><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-antique-gold">Tinh thể phong thủy</p><h1 className="mt-4 font-serif text-5xl text-ivory md:text-7xl">{stone.name}</h1><p className="mt-6 text-lg leading-9 text-stone-mist">{stone.short_description}</p><div className="mt-6 flex flex-wrap gap-2">{stone.elements.map((item) => <span key={item} className="rounded-full border border-antique-gold/40 px-4 py-2 text-sm text-antique-gold">Mệnh {item}</span>)}{stone.colors.map((item) => <span key={item} className="rounded-full border border-gilded/50 px-4 py-2 text-sm text-stone-mist">{item}</span>)}</div></div></section>
  {images.length > 1 ? <section className="mb-10"><h2 className="font-serif text-3xl text-ivory">Thư viện ảnh</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{images.map((url, index) => <StoneImage key={url} src={url} alt={`${stone.name} - ảnh ${index + 1}`} square />)}</div></section> : null}<div className="grid gap-10 lg:grid-cols-[1fr_300px]"><div>{stone.content ? <section className="border-t border-gilded/30 py-9"><MarkdownContent content={stone.content} /></section> : null}<TextSection title="Công dụng và ý nghĩa" value={stone.benefits} /><TextSection title="Đối tượng phù hợp" value={stone.suitable_for} /><TextSection title="Nguồn gốc" value={stone.origin} /></div><aside className="h-fit rounded-lg border border-gilded/40 bg-card-deep/75 p-5 lg:sticky lg:top-24"><h2 className="font-serif text-2xl text-ivory">Tương hợp</h2><dl className="mt-4 grid gap-4 text-sm text-stone-mist"><div><dt className="text-antique-gold">Mệnh</dt><dd>{stone.elements.join(", ") || "Đang cập nhật"}</dd></div><div><dt className="text-antique-gold">Cung hoàng đạo</dt><dd>{stone.zodiac_signs.join(", ") || "Đang cập nhật"}</dd></div></dl></aside></div>
  {stone.jars.length ? <section className="mt-14 border-t border-gilded/30 pt-10"><h2 className="font-serif text-4xl text-ivory">Lọ đá có sử dụng {stone.name}</h2><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{stone.jars.map((jar) => <StoneJarCard key={jar.id} jar={jar} />)}</div></section> : null}</div></main><Footer /></>; }
